export const NAVIGATION = {
    WALKTHROUGH: "WALKTHROUGH",
    LOGIN : "LOGIN",
    SIGNUP : "SIGNUP",
    FORGOTPASS : "FORGOTPASSWORD",
    HOMESCREEN : "HOMESCREEN",
    ADDNOTE : "ADDNOTE",
}




