// export const NAVIGATION = {
//     WALKTHROUGH: "WALKTHROUGH",
//     LOGIN : "LOGIN",
//     SIGNUP : "SIGNUP",
//     FORGOTPASS : "FORGOTPASSWORD",
//     HOMESCREEN : "HOMESCREEN",
//     ADDNOTE : "ADDNOTE",
//     NOTESCREEN:"NOTESCREEN",
//     SETTINGS : "SETTINGS",
//     HOME:"HOME",
//     CHECKLIST:"CHECKLIST",
//     LAMP:"LAMP",
// }

export const NAVIGATION = {
    WALKTHROUGH: "WALKTHROUGH",
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    FORGOTPASS: "FORGOTPASS",
    HOMESCREEN: "HOMESCREEN",
    ADDNOTE: "ADDNOTE",
    NOTESCREEN: "NOTESCREEN",
    SETTINGS: "SETTINGS",
    HOME: "HOME",
    CHECKLIST: "CHECKLIST",
    LAMP: "LAMP",
    ACCOUNT:"ACCOUNT",
  } as const;
  
  type NavigationRoutes = keyof typeof NAVIGATION;



